services:
  orders-api:
    container_name: btg-challenge-orders-api-prd
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/orders-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      MongoDB__ConnectionString: mongodb://root:root@mongodb:27017
      MongoDB__DatabaseName: btgpactual
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Queue: orders
      RabbitMQ__Username: admin
      RabbitMQ__Password: admin
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  rabbitmq:
    container_name: btg-challenge-rabbitmq-prd
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mongodb:
    container_name: btg-challenge-mongodb-prd
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: btgpactual
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
